### PR TITLE
Optimise scalar check to succeed fast if the 4th MSB is unset.

### PR DESCRIPTION
**Pull request by isislovecruft**
This is only done upon signature deserialisation/verification.
cf. https://github.com/dalek-cryptography/ed25519-dalek/pull/99 for more info.

### CODE REVIEW

**Comment by elichai** [comment]
You need to replace `if (input[63] & 240 == 0)` with `if ((input[63] & 240) == 0)` in Java :)

**Comment by isislovecruft** [comment]
Aha, thank you! I _knew_ I was going to mess up a Java thing since it's been a good decade or so. I even had to look up Java scoping rules for variable declarations to write this simple patch! :)

Will fix.

**Comment by elichai** [comment]
heh, languages are weird lol
I'm even scared to use bitwise and in languages I don't know without making sure it does the same thing I'm using to it doing lol

**Comment by isislovecruft** [comment]
Hmm, I should probably also do something about that code coverage drop.

**Pull request merged**
